### ISSUE TITLE
Build errors in instruments_manager.cpp under MSVC

### ISSUE THREAD

**Issue by nyanpasu64** [BambooTracker/BambooTracker#216] opened 2020-05-24 07:58 UTC
When trying to compile BambooTracker in MSVC, I get multiple errors in instruments_manager.cpp, including:

https://github.com/rerrahkr/BambooTracker/blob/a22c8228ad65b52c6f9aea3d9ecdf0d5305b0425/BambooTracker/instrument/instruments_manager.cpp#L936-L938

Basically every time you try to assign `auto something = boolExpr ? [](){} : [](){}`, compilation fails.

> error: C2446: ':': no conversion from 'InstrumentsManager::findFirstAssignableEnvelopeFM::<lambda_de615644423709b816830ef880da09c9>' to 'InstrumentsManager::findFirstAssignableEnvelopeFM::<lambda_0c25a66591cf5c218fd1a6a39e939e75>'

It builds fine in GCC, however https://stackoverflow.com/questions/48397297 suggests BambooTracker's code isn't valid C++, since different lambdas are different types. I'm not sure though.

**Comment by OPNA2608** [comment] 2020-05-24 13:10
> however https://stackoverflow.com/questions/48397297 suggests BambooTracker's code isn't valid C++

I've tested compilation with very standard-pedantic settings (`-Wall -Wextra -Werror -pedantic -pedantic-errors`) on GCC *and* Clang just now, and although I do see several compliancy problems across the codebase (our own + included code), I can't reproduce the exact exception you got at all. ~~Are we sure MSVC isn't just a special child in this case?~~

As a quick and dirty fix, [a patch like this](https://github.com/rerrahkr/BambooTracker/files/4673355/fix-msvc.txt) might fix it for you? Boils down to something like
```patch
diff --git a/BambooTracker/instrument/instruments_manager.cpp b/BambooTracker/instrument/instruments_manager.cpp
index 3c58d80..57b91fe 100644
--- a/BambooTracker/instrument/instruments_manager.cpp
+++ b/BambooTracker/instrument/instruments_manager.cpp
@@ -3,6 +3,7 @@
 #include <unordered_map>
 #include <algorithm>
 #include "instrument.hpp"
+#include <functional>
 
 const FMEnvelopeParameter InstrumentsManager::ENV_FM_PARAMS_[38] = {
 	FMEnvelopeParameter::AL,
@@ -933,9 +934,9 @@ std::vector<int> InstrumentsManager::getEnvelopeFMEntriedIndices() const
 
 int InstrumentsManager::findFirstAssignableEnvelopeFM() const
 {
-	auto cond = regardingUnedited_
-				? [](const std::shared_ptr<EnvelopeFM>& env) { return (env->isUserInstrument() || env->isEdited()); }
-	: [](const std::shared_ptr<EnvelopeFM>& env) { return env->isUserInstrument(); };
+	std::function<bool(const std::shared_ptr<EnvelopeFM>&)> cond = regardingUnedited_
+		? [](const std::shared_ptr<EnvelopeFM>& env) { return (env->isUserInstrument() || env->isEdited()); }
+		: [](const std::shared_ptr<EnvelopeFM>& env) { return env->isUserInstrument(); };
 	auto&& it = std::find_if_not(envFM_.begin(), envFM_.end(), cond);
 
 	if (it == envFM_.end()) return -1;
```
…for every instance of such a lambdas-in-ternary expression. Would that be enough to get the compilation further for now?

---

> When trying to compile BambooTracker in MSVC, I get multiple errors […]

If there's any more problems with compiling on MSVC that you'd like to point out and discuss, i think you should feel free to escalate this issue into a general MSVC compilation one.

**Comment by rerrahkr** [comment] 2020-05-24 15:26
I tested that patch on MSVC2017, but still had errors due to ternary operators. When replacing them with if-else, it works well.

```diff
@@ -933,9 +934,11 @@ std::vector<int> InstrumentsManager::getEnvelopeFMEntriedIndices() const

 int InstrumentsManager::findFirstAssignableEnvelopeFM() const
 {
-       auto cond = regardingUnedited_
-                               ? [](const std::shared_ptr<EnvelopeFM>& env) { return (env->isUserInstrument() || env->isEdited()); }
-       : [](const std::shared_ptr<EnvelopeFM>& env) { return env->isUserInstrument(); };
+       std::function<bool(const std::shared_ptr<EnvelopeFM>&)> cond;
+       if (regardingUnedited_)
+               cond = [](const std::shared_ptr<EnvelopeFM>& env) { return (env->isUserInstrument() || env->isEdited()); };
+       else
+               cond =[](const std::shared_ptr<EnvelopeFM>& env) { return env->isUserInstrument(); };
        auto&& it = std::find_if_not(envFM_.begin(), envFM_.end(), cond);

        if (it == envFM_.end()) return -1;

```

**Comment by nyanpasu64** [comment] 2020-05-24 20:21
My concern is that std::function requires a heap allocation which is slower. If this is only called on the GUI and not audio thread, it's probably not an issue in practice. What if you used a C-style function pointer instead of std::function?

**Comment by nyanpasu64** [comment] 2020-05-25 00:37
https://stackoverflow.com/questions/27989031/msvc-error-when-using-capture-less-lambda-expressions-as-second-and-third-operan

> Since neither lambda capture they can be converted to function pointers with compatible signatures, so gcc and clang are correct here.

> Filed a bug report.

> Microsoft Connect Has Been Retired

**Comment by rerrahkr** [comment] 2020-05-25 11:18
> If this is only called on the GUI and not audio thread, it's probably not an issue in practice.

Functions `InstrumentsManager::findFirstAssignable***` using those lambdas are only called on operations adding/importing instrument, that is GUI event.

**Comment by OPNA2608** [comment] 2021-08-02 12:48
Seems to not be an issue anymore. #398 fixed general compilation with MSVC2019 any didn't have to touch the instrument manager. Closing.

**Closed by OPNA2608** 2021-08-02 12:48 UTC
