### ISSUE TITLE
[Windows|macOS|Linux|BSD] - SSG distortion/aliasing

### ISSUE THREAD

**Issue by freq-mod** [BambooTracker/BambooTracker#347] opened 2021-03-21 08:19 UTC
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

I'm aware you may be currently busy and this bug might be hard to fix completely (let's hope not), but it's a thing that bothers some people nevertheless. As reported by @Iyatemu on Discord server, SSG emulation inBamboo Tracker is off, especially at higher pitches, compared to the real chip:
[alias.zip](https://github.com/rerrahkr/BambooTracker/files/6177041/alias.zip) - recording showcasing the problem. 0:00 ~ 0:04 is BT, 0:05 onware is the real YM2608 interface. Difference is apparent.

The way to fix this? I'm not sure at all, maybe via #262? (SSG core was also updated).

**Comment by rerrahkr** [comment] 2021-03-21 14:17
Thanks for your report. I suspect the use of improper linear resampling to be the cause of the distortion. I'll change to sinc resampling as mentioned in #321 and check the sound.

**Comment by rerrahkr** [comment] 2022-12-15 13:02
This issue would have fixed by using [blip-buf](https://code.google.com/archive/p/blip-buf/) since b1a6d2ea2319527e760afb8c74453d9dc025f21e.

**Closed** 2022-12-15 15:13 UTC
Labels: bug
